name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Selecciona una opción'
        required: true
        type: choice
        options:
          - Java 6
          - Java 8

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Asignar input a variable de entorno
        run: |
          echo "ENTORNO=${{ github.event.inputs.entorno }}" >> $GITHUB_ENV

      - name: Mostrar mensaje de ejecución
        run: |
          echo "El entorno seleccionado es: $ENTORNO"
