name: Manual Workflow Execution

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Mensaje personalizado'
        required: true
        type: string

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Asignar input a variable de entorno
        run: |
          echo "MENSAJE=${{ github.event.inputs.mensaje }}" >> $GITHUB_ENV

      - name: Mostrar mensaje de ejecución
        run: |
          echo "El workflow se ejecutó manualmente con el mensaje: $MENSAJE"
